### ISSUE TITLE
Scripts rely on undocumented git aliases

### ISSUE THREAD

**Issue by samueldr** [nathanchance/stable-patches#1]
Hi,

It looks like the scripts are using git aliases that are not documented as part of this repository. `git cf` and `git fp`, among others. ~I did not see a dotfiles or equivalent~

The aliases are present in the [`scripts`](https://github.com/nathanchance/scripts/blob/master/funcs/git#L37) repository. In case this is useful for anybody else.

(Btw thanks for the amazing work on android-linux-stable!)

**Comment by nathanchance** [comment]
Indeed. This is technically a personal repository, thus why this is not documented :)

**Comment by samueldr** [comment]
Not stating that it isn't a personal repository, but the `android-linux-stable` repo links to this repository for conflict resolution.

> NOTE: As of 3.18.103 and 4.4.127, these notes will no longer be updated since it takes me way too long to document them all. You can see my conflict resolutions in [my stable-patches repository](https://github.com/nathanchance/stable-patches) and you are free to reach out to me if you have any questions.

I figure other users might end up here while working towards the same goal :).
